language: C
dist: trusty
sudo: true

script:
  - wget -c "http://ftpmirror.gnu.org/emacs/emacs-25.1.tar.gz"
  - tar xf emacs-*tar.gz
  - cd emacs*
  - sudo apt-get build-dep emacs24
  - ./autogen.sh
  - ./configure --prefix=/app
  - make
  - sudo make install
  - cd ..
  - bash -ex appimage.sh
