language: C
dist: xenial
sudo: true

script:
  - export VERSION=$(wget -q "https://ftp.gnu.org/pub/gnu/emacs/?C=M;O=D" -O - | grep -oe ">emacs-.*tar.gz" | head -n 1 | cut -d - -f 2 | sed -e 's|.tar.gz||g')
  - wget -c "http://ftpmirror.gnu.org/emacs/emacs-${VERSION}.tar.gz"
  - tar xf emacs-*tar.gz
  - cd emacs*/
  - sudo apt-get build-dep emacs24
  - sudo apt-get -y install libgtk-3-dev libwebkitgtk-3.0-dev
  - ./autogen.sh
  - ./configure --prefix=/usr --without-selinux --with-x-toolkit=gtk3
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - cp appdir/usr/share/icons/hicolor/128x128/apps/emacs.png appdir/
  - wget -c -nv https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./appimagetool-*.AppImage
  - file appdir/usr/bin/emacs-*
  - ./appimagetool-*.AppImage -s deploy appdir/usr/share/applications/*.desktop
  - rm appdir/AppRun ; cp ../AppRun ./appdir/ ; chmod +x ./appdir/AppRun # Because we need some extra envs
  - sed -i -e 's|/usr|././|g' appdir/usr/bin/emacs-*
  - ( cd appdir/usr/bin/ ; rm emacs ; ln -s emacs-* emacs )
  - rm -rf appdir/usr/share/metainfo # FIXME; let it in once we can validate it
  - LD_LIBRARY_PATH='' find appdir -type f -exec ldd {} 2>&1 \; | grep '=>' | grep -v appdir
  - ./appimagetool-*.AppImage appdir/

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
