language: C
dist: trusty
sudo: true

env:
  - RELEASE_VERSION=25.1
  
script:
  - wget -c "http://ftpmirror.gnu.org/emacs/emacs-${RELEASE_VERSION}.tar.gz"
  - tar xf emacs-*tar.gz
  - cd emacs*
  - sudo apt-get build-dep emacs24
  - sudo apt-get -y remove libselinux-dev
  - ./autogen.sh
  - ./configure --prefix=/app --without-selinux
  - make
  - sudo make install
  - cd ..
  - sudo apt-get -y install squashfs-tools
  - bash -ex appimage.sh
